global_path: 'C:/Users/jaulab/Desktop/deepAAD_project'
global_data_path: 'C:/Users/jaulab/Desktop/AAD/Data'
# global_path: 'C:/Users/garcia.127407/Desktop/DNN_AAD/deepAAD_project'
# global_data_path: 'D:\igarcia\AAD_Data'

exp_name: 'batch_size'

runs: # All models trained with window size of 5s

- model: 'CNN'
  train_params:
    batch_size: 64              
    max_epoch: 200              
    lr: 2e-05
    weight_decay: 1e-08                      
    early_stopping_patience: 5
    scheduler_patience: 2
    shuffle: False
  dataset_params:
    window: 50
    hop: 1
    norm_stim: False
    data_type: 'mat'
    fixed: False
    rnd_trials: False
    window_pred: False
    hrtf: True
  loss_params:
    mode: 'corr_ild_mae'
    alpha_end: 0.02
  model_params:
    F1: 16
    D: 16
    F2: 128
    AP1: 2
    AP2: 4
    dropout: 0.3
    input_samples: 50
    output_dim: 2

- model: 'CNN'
  train_params:
    batch_size: 128              
    max_epoch: 200              
    lr: 2e-05
    weight_decay: 1e-08                      
    early_stopping_patience: 5
    scheduler_patience: 2
    shuffle: False
  dataset_params:
    window: 50
    hop: 1
    norm_stim: False
    data_type: 'mat'
    fixed: False
    rnd_trials: False
    window_pred: False
    hrtf: True
  loss_params:
    mode: 'corr_ild_mae'
    alpha_end: 0.02
  model_params:
    F1: 16
    D: 16
    F2: 128
    AP1: 2
    AP2: 4
    dropout: 0.3
    input_samples: 50
    output_dim: 2

  - model: 'CNN'
  train_params:
    batch_size: 320              
    max_epoch: 200              
    lr: 2e-05
    weight_decay: 1e-08                      
    early_stopping_patience: 5
    scheduler_patience: 2
    shuffle: False
  dataset_params:
    window: 50
    hop: 1
    norm_stim: False
    data_type: 'mat'
    fixed: False
    rnd_trials: False
    window_pred: False
    hrtf: True
  loss_params:
    mode: 'corr_ild_mae'
    alpha_end: 0.02
  model_params:
    F1: 16
    D: 16
    F2: 128
    AP1: 2
    AP2: 4
    dropout: 0.3
    input_samples: 50
    output_dim: 2

  - model: 'CNN'
  train_params:
    batch_size: 320              
    max_epoch: 200              
    lr: 2e-05
    weight_decay: 1e-08                      
    early_stopping_patience: 5
    scheduler_patience: 2
    shuffle: False
  dataset_params:
    window: 128
    hop: 1
    norm_stim: False
    data_type: 'mat'
    fixed: False
    rnd_trials: False
    window_pred: False
    hrtf: True
  loss_params:
    mode: 'corr_ild_mae'
    alpha_end: 0.02
  model_params:
    F1: 16
    D: 16
    F2: 128
    AP1: 2
    AP2: 4
    dropout: 0.3
    input_samples: 50
    output_dim: 2