global_path: 'C:/Users/jaulab/Desktop/deepAAD_project'
global_data_path: 'C:/Users/jaulab/Desktop/AAD/Data'
# global_path: 'C:/Users/garcia.127407/Desktop/DNN_AAD/deepAAD_project'
# global_data_path: 'D:\igarcia\AAD_Data'

exp_name: 'mean_hrtfs_dnn'

runs: # All models trained with window size of 5s

  - model: 'FCNN'
    train_params:
      batch_size: 128              
      max_epoch: 200              
      lr: 1e-06
      weight_decay: 1e-04                      
      early_stopping_patience: 5
      scheduler_patience: 2
    dataset_params:
      window_len: 50  
      hop: 1          
      filt: False       
      fixed: False      
      rnd_trials: False   
      window_pred: False
      hrtf: True
    model_params:
      n_hidden: 3
      dropout: 0.45
      n_samples: 50
      output_dim: 2

  # - model: 'FCNN'
  #   train_params:
  #     batch_size: 64              
  #     max_epoch: 200              
  #     lr: 1e-06
  #     weight_decay: 1e-04                      
  #     early_stopping_patience: 5
  #     scheduler_patience: 2
  #   dataset_params:
  #     window_len: 128  
  #     hop: 1          
  #     filt: False       
  #     fixed: False      
  #     rnd_trials: False   
  #     window_pred: True
  #     hrtf: False
  #   model_params:
  #     n_hidden: 3
  #     dropout: 0.45
  #     n_samples: 128
  #     output_dim: 128

  - model: 'CNN'
    train_params:
      batch_size: 128              
      max_epoch: 200              
      lr: 2e-05
      weight_decay: 1e-08                      
      early_stopping_patience: 5
      scheduler_patience: 2
    dataset_params:
      window_len: 50  
      hop: 1          
      filt: False       
      fixed: False      
      rnd_trials: False   
      window_pred: False
      hrtf: True
    model_params:
      F1: 8
      D: 8
      F2: 64
      AP1: 2
      AP2: 4
      dropout: 0.2
      input_samples: 50
      output_dim: 2

  - model: 'Conformer'
    train_params:
      batch_size: 128              
      max_epoch: 200              
      lr: 1e-06
      weight_decay: 1e-04                      
      early_stopping_patience: 5
      scheduler_patience: 2
    dataset_params:
      window_len: 128  
      hop: 1          
      filt: False       
      fixed: False      
      rnd_trials: False   
      window_pred: False
      hrtf: True
    model_params:
      mlp_ratio: 2
      enc_layers: 2
      n_head: 4
      n_embd: 40
      kernel_temp: 8
      pool: 10
      pool_hop: 4
      block_size: 128 # 2s
      dropout: 0.4
      classifier: True
      bias: True
      output_dim: 2