global_path: 'C:/Users/jaulab/Desktop/deepAAD_project'
global_data_path: 'C:/Users/jaulab/Desktop/AAD/Data'
# global_path: 'C:/Users/garcia.127407/Desktop/DNN_AAD/deepAAD_project'
# global_data_path: 'D:\igarcia\AAD_Data'

exp_name: 'locus_best_models'

runs: # All models trained with window size of 5s

  - model: 'CNN'
    train_params:
      batch_size: 320              
      max_epoch: 200              
      lr: 2e-05
      weight_decay: 1e-08                      
      early_stopping_patience: 5
      scheduler_patience: 2
      loss_mode: 'spatial_locus'
    dataset_params:
      window_len: 50  
      hop: 1          
      filt: False       
      fixed: False      
      rnd_trials: False   
      window_pred: False
      spatial_locus: True
      shuffle: True
    model_params:
      F1: 16
      D: 8
      AP1: 2
      AP2: 4
      dropout: 0.2
      input_samples: 50
      output_dim: 1

  # - model: 'CNN'
  #   train_params:
  #     batch_size: 128              
  #     max_epoch: 200              
  #     lr: 2e-05
  #     weight_decay: 1e-08                      
  #     early_stopping_patience: 5
  #     scheduler_patience: 2
  #     loss_mode: 'spatial_locus'
  #   dataset_params:
  #     window_len: 128  
  #     hop: 1          
  #     filt: False       
  #     fixed: False      
  #     rnd_trials: False   
  #     window_pred: False
  #     spatial_locus: True
  #     shuffle: True
  #   model_params:
  #     F1: 8
  #     D: 16
  #     AP1: 2
  #     AP2: 4
  #     dropout: 0.4
  #     input_samples: 128
  #     output_dim: 1

  # - model: 'CNN'
  #   train_params:
  #     batch_size: 320              
  #     max_epoch: 200              
  #     lr: 2e-05
  #     weight_decay: 1e-08                      
  #     early_stopping_patience: 3
  #     scheduler_patience: 2
  #     loss_mode: 'spatial_locus'
  #     batch_rnd_sampler: True
  #   dataset_params:
  #     window_len: 50  
  #     hop: 1          
  #     filt: False       
  #     fixed: False      
  #     rnd_trials: False   
  #     window_pred: False
  #     spatial_locus: True
  #   model_params:
  #     F1: 16
  #     D: 8
  #     AP1: 2
  #     AP2: 4
  #     dropout: 0.2
  #     input_samples: 50
  #     output_dim: 1

  # - model: 'CNN'
  #   train_params:
  #     batch_size: 128              
  #     max_epoch: 200              
  #     lr: 2e-05
  #     weight_decay: 1e-08                      
  #     early_stopping_patience: 3
  #     scheduler_patience: 2
  #     loss_mode: 'spatial_locus'
  #     batch_rnd_sampler: True
  #   dataset_params:
  #     window_len: 128  
  #     hop: 1          
  #     filt: False       
  #     fixed: False      
  #     rnd_trials: False   
  #     window_pred: False
  #     spatial_locus: True
  #   model_params:
  #     F1: 8
  #     D: 16
  #     AP1: 2
  #     AP2: 4
  #     dropout: 0.4
  #     input_samples: 128
  #     output_dim: 1


  