global_path: 'C:/Users/jaulab/Desktop/deepAAD_project'
global_data_path: 'C:/Users/jaulab/Desktop/AAD/Data'
# global_path: 'C:/Users/garcia.127407/Desktop/DNN_AAD/deepAAD_project'
# global_data_path: 'D:\igarcia\AAD_Data'

exp_name: 'ild_criterion'

runs: # All models trained with window size of 5s

  - model: 'CNN'
    train_params:
      batch_size: 128              
      max_epoch: 200              
      lr: 2e-05
      weight_decay: 1e-08                      
      early_stopping_patience: 5
      scheduler_patience: 2
      shuffle: True
    dataset_params:
      window: 50
      hop: 1
      norm_stim: False
      data_type: 'mat'
      fixed: False
      rnd_trials: False
      window_pred: False
      spatial_locus: True
    loss_params:
      mode: 'spatial_locus'
    model_params:
      F1: 8
      D: 8
      AP1: 2
      AP2: 4
      dropout: 0.2
      input_samples: 50
      output_dim: 1