global_path: 'C:/Users/jaulab/Desktop/deepAAD_project'
global_data_path: 'C:/Users/jaulab/Desktop/AAD/Data'
# global_path: 'C:/Users/garcia.127407/Desktop/DNN_AAD/deepAAD_project'
# global_data_path: 'D:\igarcia\AAD_Data'

experiments:

  - name: 'population_fulsang_FCNN'
    key: 'population'
    dataset: 'skl'
    model: 'FCNN'
    train_params:
      batch_size: 128              
      max_epoch: 200              
      lr: 1e-06
      weight_decay: 1e-04                      
      early_stopping_patience: 5
      scheduler_patience: 2
    dataset_params:
      window_len: 50  
      hop: 1          
      filt: False       
      fixed: False      
      rnd_trials: False   
      unit_output: True
    model_params:
      n_hidden: 3
      dropout: 0.45
      n_samples: 50

  - name: 'population_fulsang_Conformer'
    key: 'subj_specific'
    dataset: 'fulsang'
    model: 'Conformer'
    train_params:
      batch_size: 128              
      max_epoch: 200              
      lr: 2e-05
      weight_decay: 1e-08                      
      early_stopping_patience: 5
      scheduler_patience: 2
    dataset_params:
      window_len: 50  
      hop: 1          
      filt: False       
      fixed: False      
      rnd_trials: False   
      unit_output: True
    model_params:
      mlp_ratio: 2
      enc_layers: 2
      n_head: 4
      n_embd: 40
      kernel_chan: 64
      kernel_temp: 8
      pool: 20
      pool_hop: 4
      block_size: 50 # 2s
      dropout: 0.4
      classifier: True
      bias: True

  - name: 'population_fulsang_CNN'
    key: 'population'
    dataset: 'fulsang'
    model: 'CNN'
    train_params:
      batch_size: 128              
      max_epoch: 200              
      lr: 2e-05
      weight_decay: 1e-08                      
      early_stopping_patience: 5
      scheduler_patience: 2
    dataset_params:
      window_len: 50  
      hop: 1          
      filt: False       
      fixed: False      
      rnd_trials: False   
      unit_output: True
    model_params:
      F1: 8
      D: 8
      F2: 64
      AP1: 2
      AP2: 4
      dropout: 0.2
      input_samples: 50
    
  - name: 'population_fulsang_VLAAI'
    key: 'population'
    dataset: 'fulsang'
    model: 'VLAAI'
    train_params:
      batch_size: 64              
      max_epoch: 200              
      lr: 3e-07
      weight_decay: 1e-04                   
      early_stopping_patience: 5
      scheduler_patience: 2
    dataset_params:
      window_len: 320  
      hop: 4          
      filt: False       
      fixed: False      
      rnd_trials: False   
      unit_output: False
    model_params:
      n_blocks: 4
      use_skip: True
      output_dim: 1
      dropout: 0.4