experiments:

  - name: 'population_fulsang_VLAAI'
    key: 'population'
    global_path: 'C:/Users/jaulab/Desktop/deepAAD_project'
    global_data_path: 'C:/Users/jaulab/Desktop/AAD/Data'
    dataset: 'fulsang'
    model: 'VLAAI'
    train_params:
      batch_size: 64              
      max_epoch: 200              
      lr: 3e-07
      weight_decay: 1e-04                   
      early_stopping_patience: 5
      scheduler_patience: 2
    dataset_params:
      window_len: 320  
      hop: 4          
      filt: False       
      fixed: False      
      rnd_trials: False   
      unit_output: False
    model_params:
      n_blocks: 4
      use_skip: True
      output_dim: 1
      dropout: 0.4

  - name: 'population_fulsang_FCNN'
    key: 'population'
    global_path: 'C:/Users/jaulab/Desktop/AAD/IA_poster'
    global_data_path: 'C:/Users/jaulab/Desktop/AAD/Data'
    dataset: 'fulsang'
    model: 'FCNN'
    train_params:
      batch_size: 32              
      max_epoch: 200              
      lr: 3e-07
      weight_decay: 1e-04                      
      early_stopping_patience: 5
      scheduler_patience: 2
    dataset_params:
      window_len: 50  
      hop: 2          
      filt: False       
      fixed: False      
      rnd_trials: False   
      unit_output: True
    model_params:
      n_hidden: 3
      dropout: 0.45
      n_samples: 50