global_path: 'C:/Users/jaulab/Desktop/deepAAD_project'
global_data_path: 'C:/Users/jaulab/Desktop/AAD/Data'
# global_path: 'C:/Users/garcia.127407/Desktop/DNN_AAD/deepAAD_project'
# global_data_path: 'D:\igarcia\AAD_Data'

experiments:

  - name: 'population_fulsang_FCNN'
    key: 'population'
    dataset: 'fulsang'
    model: 'FCNN'
    train_params:
      batch_size: 128              
      max_epoch: 200              
      lr: 3e-07
      weight_decay: 1e-04                      
      early_stopping_patience: 5
      scheduler_patience: 2
    dataset_params:
      window_len: 50  
      hop: 1          
      filt: False       
      fixed: False      
      rnd_trials: False   
      unit_output: True
    model_params:
      n_hidden: 3
      dropout: 0.45
      n_samples: 50
    
  - name: 'population_fulsang_VLAAI'
    key: 'population'
    dataset: 'fulsang'
    model: 'VLAAI'
    train_params:
      batch_size: 64              
      max_epoch: 200              
      lr: 3e-07
      weight_decay: 1e-04                   
      early_stopping_patience: 5
      scheduler_patience: 2
    dataset_params:
      window_len: 320  
      hop: 4          
      filt: False       
      fixed: False      
      rnd_trials: False   
      unit_output: False
    model_params:
      n_blocks: 4
      use_skip: True
      output_dim: 1
      dropout: 0.4