# evluating different mdl sizes and complexities
global_path: 'C:/Users/jaulab/Desktop/deepAAD_project'
global_data_path: 'C:/Users/jaulab/Desktop/AAD/Data'
# global_path: 'C:/Users/garcia.127407/Desktop/DNN_AAD/deepAAD_project'
# global_data_path: 'D:\igarcia\AAD_Data'

exp_name: 'hop_size'

runs:
  
  - model: 'Conformer' # hop 1
    train_params:
      batch_size: 128              
      max_epoch: 200              
      lr: 1e-06
      weight_decay: 1e-04                     
      early_stopping_patience: 5
      scheduler_patience: 2
    dataset_params:
      window_len: 50 
      hop: 1          
      filt: False       
      fixed: False      
      rnd_trials: False   
      unit_output: True
    model_params:
      mlp_ratio: 2
      enc_layers: 4
      n_head: 4
      n_embd: 40
      kernel_temp: 8
      pool: 10
      pool_hop: 4
      block_size: 50
      dropout: 0.4
      classifier: True
      bias: True

  - model: 'Conformer' # hop 8
    train_params:
      batch_size: 128              
      max_epoch: 200              
      lr: 1e-06
      weight_decay: 1e-04                     
      early_stopping_patience: 5
      scheduler_patience: 2
    dataset_params:
      window_len: 50 
      hop: 8          
      filt: False       
      fixed: False      
      rnd_trials: False   
      unit_output: True
    model_params:
      mlp_ratio: 2
      enc_layers: 4
      n_head: 4
      n_embd: 40
      kernel_temp: 8
      pool: 10
      pool_hop: 4
      block_size: 50
      dropout: 0.4
      classifier: True
      bias: True

  - model: 'Conformer' # hop 16
    train_params:
      batch_size: 128              
      max_epoch: 200              
      lr: 1e-06
      weight_decay: 1e-04                     
      early_stopping_patience: 5
      scheduler_patience: 2
    dataset_params:
      window_len: 50 
      hop: 16          
      filt: False       
      fixed: False      
      rnd_trials: False   
      unit_output: True
    model_params:
      mlp_ratio: 2
      enc_layers: 4
      n_head: 4
      n_embd: 40
      kernel_temp: 8
      pool: 10
      pool_hop: 4
      block_size: 50
      dropout: 0.4
      classifier: True
      bias: True