global_path: 'C:/Users/jaulab/Desktop/deepAAD_project'
global_data_path: 'C:/Users/jaulab/Desktop/AAD/Data'
# global_path: 'C:/Users/garcia.127407/Desktop/DNN_AAD/deepAAD_project'
# global_data_path: 'D:\igarcia\AAD_Data'

runs:

  # - linear_model: 'CCA'
  #   model_params:
  #     encoder_len: 80
  #     decoder_len: 16
  #     n_components: 6
  #   dataset_params:
  #     fixed: False
  #     rnd_trials: False

  - linear_model: 'CCA'
    model_params:
      encoder_len: 80
      decoder_len: 16
      n_components: 6
      max_iter: 100
    dataset_params:
      fixed: False
      rnd_trials: False

  - linear_model: 'CCA'
    model_params:
      encoder_len: 80
      decoder_len: 16
      n_components: 6
      tol: 0.0001
    dataset_params:
      fixed: False
      rnd_trials: False

  # - linear_model: 'CCA'
  #   model_params:
  #     encoder_len: 80
  #     decoder_len: 16
  #     n_components: 32
  #   dataset_params:
  #     fixed: False
  #     rnd_trials: False

  # - linear_model: 'CCA'
  #   model_params:
  #     encoder_len: 80
  #     decoder_len: 26
  #     n_components: 26
  #   dataset_params:
  #     fixed: False
  #     rnd_trials: False

  # - linear_model: 'CCA'
  #   model_params:
  #     encoder_len: 20
  #     decoder_len: 16
  #     n_components: 16
  #   dataset_params:
  #     fixed: False
  #     rnd_trials: False

  # - linear_model: 'CCA'
  #   model_params:
  #     encoder_len: 160
  #     decoder_len: 16
  #     n_components: 16
  #   dataset_params:
  #     fixed: False
  #     rnd_trials: False
