# global_path: 'C:/Users/jaulab/Desktop/deepAAD_project'
# global_data_path: 'C:/Users/jaulab/Desktop/AAD/Data'
global_path: 'C:/Users/garcia.127407/Desktop/DNN_AAD/deepAAD_project'
global_data_path: 'D:\igarcia\AAD_Data'

exp_name: 'ild_sweep_local'

runs: # All models trained with window size of 5s

  - model: 'CNN'
    train_params:
      batch_size: 320              
      max_epoch: 200              
      lr: 2e-05
      weight_decay: 1e-08                      
      early_stopping_patience: 3
      shuffle: True
    dataset_params:
      window: 128
      hop: 2
      norm_stim: False
      data_type: 'mat'
      fixed: False
      rnd_trials: False
      window_pred: False
      hrtf: True
    loss_params:
      mode: 'corr_ild_mae'
      alpha_end: 0.02
    model_params:
      F1: 8
      D: 8
      F2: 64
      AP1: 2
      AP2: 4
      dropout: 0.2
      input_samples: 128
      output_dim: 2