program: sweep_models.py
project: euroacustics
method: bayes  # random, grid, bayes
metric:
  name: val_loss  # Monitored metric
  goal: minimize  # Maximize or minimize the metric
parameters:
  dropout:
    values: [0.2, 0.4]
  dropout_clsf:
    values: [0.4, 0.6]
  enc_layers: 
    values: [2, 4]
  n_embd:
    values: [32, 64]
  pool:
    values: [5, 20]
  pool_hop:
    values: [2, 5]
  hidden_size:
    values: [8, 32, 128]    
command:
  - ${env}
  - C:/Users/garce/AAD_Enviroment/Scripts/python.exe
  - ${program}
  - ${args}