global_path: 'C:/Users/jaulab/Desktop/deepAAD_project'
global_data_path: 'C:/Users/jaulab/Desktop/AAD/Data'
# global_path: 'C:/Users/garcia.127407/Desktop/DNN_AAD/deepAAD_project'
# global_data_path: 'D:\igarcia\AAD_Data'

exp_name: 'ridge_tunning'

runs:

  - linear_model: 'Ridge'
    model_params:
      start_lag: -26
      end_lag: 0
      per_trial: True
    train_params:
      preproc_mode: null
    dataset_params:
      window: 50
      hop: 1
      fixed: False
      rnd_trials: False
      window_pred: False

  # - linear_model: 'Ridge_scikit'
  #   model_params:
  #     start_lag: -26
  #     end_lag: 0
  #     per_trial: False
  #   train_params:
  #     preproc_mode: null
  #   dataset_params:
  #     window: 50
  #     hop: 1
  #     fixed: False
  #     rnd_trials: False
  #     window_pred: False

  # - linear_model: 'Ridge'
  #   model_params:
  #     start_lag: -26
  #     end_lag: 0
  #     per_trial: False
  #   train_params:
  #     preproc_mode: null
  #   dataset_params:
  #     window: 50
  #     hop: 1
  #     fixed: False
  #     rnd_trials: False
  #     window_pred: False

  # - linear_model: 'Ridge_scikit'
  #   model_params:
  #     start_lag: -26
  #     end_lag: 0
  #     per_trial: True
  #   train_params:
  #     preproc_mode: null
  #   dataset_params:
  #     window: 50
  #     hop: 1
  #     fixed: False
  #     rnd_trials: False
  #     window_pred: False