global_path: 'C:/Users/jaulab/Desktop/deepAAD_project'
global_data_path: 'C:/Users/jaulab/Desktop/AAD/Data'
# global_path: 'C:/Users/garcia.127407/Desktop/DNN_AAD/deepAAD_project'
# global_data_path: 'D:\igarcia\AAD_Data'
# global_path: 'C:/Users/garce/Desktop/proyecto_2024/deepAAD_project'
# global_data_path: 'C:/Users/garce/Desktop/proyecto_2024/Data'

exp_name: 'VLAAI_sweep'

runs:

  - model: 'VLAAI'
    train_params:
      batch_size: 64              
      max_epoch: 200              
      lr: 3e-05
      weight_decay: 1e-04                   
      early_stopping_patience: 5
      scheduler_patience: 2
      shuffle: True
    dataset_params:
      window: 320  
      hop: 32                
      fixed: False      
      rnd_trials: False   
      window_pred: True
    model_params:
      n_blocks: 4
      use_skip: True
      output_dim: 1
      dropout: 0.4
    loss_params:
      mode: 'mean'